// Generated by ./dev/css-typed/index.mts, DO NOT EDIT IT!!!
// source file: index.module.less

export const flex: string;
export const flexCol: string;
export const flex1: string;
export const justifyBetween: string;
export const justifyCenter: string;
export const itemsCenter: string;
export const textCenter: string;
export const hFull: string;
export const wFull: string;
export const truncate: string;
export const hidden: string;
export const wrapper: string;
export const container: string;
export const hcaptcha: string;
export const logo: string;
export const buttonGroup: string;
export const button: string;
