// Generated by ./dev/css-typed DO NOT EDIT IT
// source file: index.module.less

export const wrapper: string;
export const container: string;
export const hcaptcha: string;
export const logo: string;
export const buttonGroup: string;
export const button: string;
