codecov:
  require_ci_to_pass: yes

comment: false

coverage:
  precision: 2
  round: down
  range: '80...100'
  status:
    default_rules:
      flag_coverage_not_uploaded_behavior: exclude
    project:
      design:
        target: auto
        threshold: '1%'
        paths:
          - 'packages/design'
      website:
        target: auto
        threshold: 5
        paths:
          - 'packages/website'
