pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - 'created-at<=48:00 ago'
      - -conflict
      - base=master
      - '#review-threads-unresolved=0'
      - check-failure!=storybook-build
      - check-failure!=lint
      - check-failure!=test
      - check-failure!=build
    actions:
      merge:
        method: squash

  - name: request review
    conditions:
      - '#approved-reviews-by=0'
      - '#review-threads-unresolved=0'
      - '#changes-requested-reviews-by=0'
      - -conflict
      - -draft
      - base=master
      - check-failure!=storybook-build
      - check-failure!=lint
      - check-failure!=test
      - check-failure!=build
      - label!=waiting-review
    actions:
      request_reviews:
        teams:
          - '@bangumi/frontend-collaborators'
      label:
        add:
          - waiting-review

  - name: add 48h label
    conditions:
      - '#approved-reviews-by>=1'
      - -conflict
      - base=master
      - -draft
      - '#review-threads-unresolved=0'
      - check-failure!=storybook-build
      - check-failure!=lint
      - check-failure!=test
      - check-failure!=build
    actions:
      label:
        remove:
          - waiting-review
        toggle:
          - waiting-opened-48h

  - name: warn on conflicts
    conditions:
      - conflict
    actions:
      comment:
        message: '@{{author}} this pull request is now in conflict 😩'
      label:
        add:
          - conflict

  - name: remove conflict label if not needed
    conditions:
      - -conflict
    actions:
      label:
        remove:
          - conflict

  - name: toggle labels based on lint state
    conditions:
      - check-failure=lint
    actions:
      label:
        toggle:
          - 'ci:lint:fail'

  - name: toggle labels based on test state
    conditions:
      - check-failure=test
    actions:
      label:
        toggle:
          - 'ci:test:fail'

  - name: toggle labels based on build state
    conditions:
      - check-failure=build
    actions:
      label:
        toggle:
          - 'ci:build:fail'

  - name: toggle labels based on storybook build  state
    conditions:
      - check-failure=storybook-build
    actions:
      label:
        toggle:
          - 'ci:storybook-build:fail'
