pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - '#approved-reviews-by>=2'
      - 'created-at<=48:00 ago'
      - -conflict
      - base=master
      - '#review-threads-unresolved=0'
      - -title~=(?i)\[wip\]
      - -check-failure=lint
      - -check-failure=build
      - -check-failure=test
      - -check-failure=storybook-build
    actions:
      merge:
        method: squash

  - name: label 'waiting-reviewer-approval'
    conditions:
      - '#approved-reviews-by<2'
      - -conflict
      - -draft
      - base=master
      - -title~=(?i)\[wip\]
      - 'created-at<=00:10 ago' # label after PR is created after 10 min
      - -check-failure=lint
      - -check-failure=build
      - -check-failure=test
      - -check-failure=storybook-build
    actions:
      label:
        toggle:
          - waiting-approval

  - name: label waiting 48h
    conditions:
      - '#approved-reviews-by>=2'
      - '#changes-requested-reviews-by=0'
      - 'created-at>48:00 ago'
      - -conflict
      - base=master
      - -draft
      - '#review-threads-unresolved=0'
      - -title~=(?i)\[wip\]
      - -check-failure=lint
      - -check-failure=build
      - -check-failure=test
      - -check-failure=storybook-build
    actions:
      label:
        toggle:
          - waiting-opened-48h

  - name: warn on conflicts
    conditions:
      - conflict
    actions:
      comment:
        message: '@{{author}} this pull request is now in conflict 😩'
      label:
        add:
          - conflict

  - name: remove conflict label if not needed
    conditions:
      - -conflict
    actions:
      label:
        remove:
          - conflict

  - name: toggle labels based on lint state
    conditions:
      - check-failure=lint
    actions:
      label:
        toggle:
          - 'ci:lint:fail'

  - name: toggle labels based on test state
    conditions:
      - check-failure=test
    actions:
      label:
        toggle:
          - 'ci:test:fail'

  - name: toggle labels based on build state
    conditions:
      - check-failure=build
    actions:
      label:
        toggle:
          - 'ci:build:fail'

  - name: toggle labels based on storybook build  state
    conditions:
      - check-failure=storybook-build
    actions:
      label:
        toggle:
          - 'ci:storybook-build:fail'

queue_rules:
  - name: default
    merge_method: squash
    merge_conditions:
      - -conflict
      - -check-failure=lint
      - -check-failure=build
      - -check-failure=test
      - -check-failure=storybook-build
