pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - '#approved-reviews-by>=2'
      - 'created-at<=48:00 ago'
      - -conflict
      - base=master
      - '#review-threads-unresolved=0'
      - -title~=(?i)\[wip\]
      - or:
          - check-success=storybook-build
          - check-skipped=storybook-build
      - or:
          - check-success=lint
          - check-skipped=lint
      - or:
          - check-success=test
          - check-skipped=test
      - or:
          - check-success=build
          - check-skipped=build
    actions:
      merge:
        method: squash

  - name: label 'waiting-reviewer-approval'
    conditions:
      - '#approved-reviews-by<2'
      - -conflict
      - -draft
      - base=master
      - label!=waiting-review
      - -title~=(?i)\[wip\]
      - or:
          - check-success=storybook-build
          - check-skipped=storybook-build
      - or:
          - check-success=lint
          - check-skipped=lint
      - or:
          - check-success=test
          - check-skipped=test
      - or:
          - check-success=build
          - check-skipped=build
    actions:
      label:
        toggle:
          - waiting-reviewer-approval

  - name: label waiting 48h
    conditions:
      - '#approved-reviews-by>=2'
      - '#changes-requested-reviews-by=0'
      - -conflict
      - base=master
      - -draft
      - '#review-threads-unresolved=0'
      - -title~=(?i)\[wip\]
      - or:
          - check-success=storybook-build
          - check-skipped=storybook-build
      - or:
          - check-success=lint
          - check-skipped=lint
      - or:
          - check-success=test
          - check-skipped=test
      - or:
          - check-success=build
          - check-skipped=build
    actions:
      label:
        toggle:
          - waiting-opened-48h-before-merge

  - name: warn on conflicts
    conditions:
      - conflict
    actions:
      comment:
        message: '@{{author}} this pull request is now in conflict 😩'
      label:
        add:
          - conflict

  - name: remove conflict label if not needed
    conditions:
      - -conflict
    actions:
      label:
        remove:
          - conflict

  - name: toggle labels based on lint state
    conditions:
      - check-failure=lint
    actions:
      label:
        toggle:
          - 'ci:lint:fail'

  - name: toggle labels based on test state
    conditions:
      - check-failure=test
    actions:
      label:
        toggle:
          - 'ci:test:fail'

  - name: toggle labels based on build state
    conditions:
      - check-failure=build
    actions:
      label:
        toggle:
          - 'ci:build:fail'

  - name: toggle labels based on storybook build  state
    conditions:
      - check-failure=storybook-build
    actions:
      label:
        toggle:
          - 'ci:storybook-build:fail'
