pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - '#approved-reviews-by>=2'
      - 'created-at<=48:00 ago'
      - -conflict
      - base=master
      - '#review-threads-unresolved=0'
      - -title~=(?i)\[wip\]
      - and: &ci
          - -check-failure=lint
          - -check-failure=build
          - -check-failure=test
          - -check-failure=storybook-build
    actions:
      merge:
        method: squash

  - name: add label 'waiting-approval'
    conditions:
      - '#approved-reviews-by<2'
      - -label=waiting-approval
      - and: &basic-pr
          - -conflict
          - -draft
          - base=master
          - -title~=(?i)\[wip\]
      - or:
          - check-success=lint
          - check-neutral=lint
          - check-skipped=lint
      - or:
          - check-success=build
          - check-neutral=build
          - check-skipped=build
      - or:
          - check-success=test
          - check-neutral=test
          - check-skipped=test
      - or:
          - check-success=storybook-build
          - check-neutral=storybook-build
          - check-skipped=storybook-build
    actions:
      label:
        add:
          - waiting-approval

  - name: remove label 'waiting-approval'
    conditions:
      - and: *basic-pr
      - label=waiting-approval
      - or:
          - check-failure=lint
          - check-failure=build
          - check-failure=test
          - check-failure=storybook-build
    actions:
      label:
        remove:
          - waiting-approval

  - name: label waiting 48h
    conditions:
      - '#approved-reviews-by>=2'
      - '#changes-requested-reviews-by=0'
      - 'created-at>48:00 ago'
      - -conflict
      - base=master
      - -draft
      - '#review-threads-unresolved=0'
      - -title~=(?i)\[wip\]
      - and: *ci
    actions:
      label:
        toggle:
          - waiting-opened-48h

  - name: warn on conflicts
    conditions:
      - conflict
    actions:
      comment:
        message: '@{{author}} this pull request is now in conflict 😩'
      label:
        add:
          - conflict

  - name: remove conflict label if not needed
    conditions:
      - -conflict
    actions:
      label:
        remove:
          - conflict

  - name: toggle labels based on lint state
    conditions:
      - check-failure=lint
    actions:
      label:
        toggle:
          - 'ci:lint:fail'

  - name: toggle labels based on test state
    conditions:
      - check-failure=test
    actions:
      label:
        toggle:
          - 'ci:test:fail'

  - name: toggle labels based on build state
    conditions:
      - check-failure=build
    actions:
      label:
        toggle:
          - 'ci:build:fail'

  - name: toggle labels based on storybook build  state
    conditions:
      - check-failure=storybook-build
    actions:
      label:
        toggle:
          - 'ci:storybook-build:fail'
