pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - '#approved-reviews-by>=2'
    actions:
      merge:
        method: merge

  - name: warn on conflicts
    conditions:
      - conflict
    actions:
      comment:
        message: '@{{author}} this pull request is now in conflict 😩'
      label:
        add:
          - conflict

  - name: remove conflict label if not needed
    conditions:
      - -conflict
    actions:
      label:
        remove:
          - conflict

  - name: toggle labels based on lint state
    conditions:
      - check-failure=Lint / lint (pull_request)
    actions:
      label:
        toggle:
          - 'ci:lint:fail'

  - name: toggle labels based on test state
    conditions:
      - check-failure=Unit Test / test (pull_request)
    actions:
      label:
        toggle:
          - 'ci:test:fail'

  - name: toggle labels based on build state
    conditions:
      - check-failure=Build / build (pull_request)
    actions:
      label:
        toggle:
          - 'ci:build:fail'
