pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - '#approved-reviews-by>=1'
      - 'created-at>48 hours ago'
      - -conflict
      - base=master
    actions:
      merge:
        method: squash

  - name: warn on conflicts
    conditions:
      - conflict
    actions:
      comment:
        message: '@{{author}} this pull request is now in conflict 😩'
      label:
        add:
          - conflict

  - name: remove conflict label if not needed
    conditions:
      - -conflict
    actions:
      label:
        remove:
          - conflict

  - name: toggle labels based on lint state
    conditions:
      - check-failure=lint
    actions:
      label:
        toggle:
          - 'ci:lint:fail'

  - name: toggle labels based on test state
    conditions:
      - check-failure=test
    actions:
      label:
        toggle:
          - 'ci:test:fail'

  - name: toggle labels based on build state
    conditions:
      - check-failure=build
    actions:
      label:
        toggle:
          - 'ci:build:fail'

  - name: toggle labels based on storybook build  state
    conditions:
      - check-failure=storybook-build
    actions:
      label:
        toggle:
          - 'ci:storybook-build:fail'
