import * as path from 'node:path';
import * as url from 'node:url';

import camelcase from 'camelcase';
import * as css from 'css-tree';
import less from 'less';

const __dirname = url.fileURLToPath(new URL('.', import.meta.url));

// 跟 '<projectRoot>/packages/website/vite.config.ts' 保持同步
const lessAdditionalData = '@import "./src/style/utils.less";';

export async function generateDeclaration(p: string, content: string) {
  const filename = path.basename(p);
  const dirname = path.dirname(p);
  if (filename.endsWith('.less')) {
    const o = await less.render(lessAdditionalData + '\n' + content, {
      filename,
      paths: [path.join(__dirname, '../..', 'packages/website'), dirname],
    });
    content = o.css;
  }

  let ts = `// Generated by ./dev/css-typed/index.mts, DO NOT EDIT IT!!!\n// source file: ${filename}\n\n`;
  const ast = css.parse(content, { filename });
  const classNames = new Set<string>();
  css.walk(ast, (node) => {
    if (node.type === `ClassSelector`) {
      classNames.add(camelcase(node.name));
    }
  });

  classNames.forEach((name) => {
    ts += `export const ${name}: string;\n`;
  });

  return ts;
}
