codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: '80...100'
  status:
    default_rules:
      flag_coverage_not_uploaded_behavior: exclude
    project:
      design:
        target: '80%'
        threshold: 0
        paths:
          - 'packages/design'
      website:
        target: '80%'
        threshold: 5
        paths:
          - 'packages/website'
