// Generated by ./dev/css-typed/index.mts, DO NOT EDIT IT!!!
// source file: SubMenu.module.less

export const flex: string;
export const flexCol: string;
export const flex1: string;
export const justifyBetween: string;
export const justifyCenter: string;
export const itemsCenter: string;
export const textCenter: string;
export const hFull: string;
export const wFull: string;
export const truncate: string;
export const hidden: string;
export const smScreenHidden: string;
export const noTopBorder: string;
export const noBottomBorder: string;
export const subMenu: string;
export const subMenuDivider: string;
export const subMenuItemDo: string;
export const subMenuItemWish: string;
export const subMenuItemCollect: string;
export const subMenuItemOnHold: string;
export const subMenuItemDropped: string;
