// Generated by ./dev/css-typed DO NOT EDIT IT
// source file: SubMenu.module.less

export const smScreenHidden: string;
export const noTopBorder: string;
export const noBottomBorder: string;
export const subMenu: string;
export const subMenuDivider: string;
export const subMenuItemDo: string;
export const subMenuItemWish: string;
export const subMenuItemCollect: string;
export const subMenuItemOnHold: string;
export const subMenuItemDropped: string;
