// Generated by ./dev/css-typed
// source file: style.module.less

export const smScreenHidden: string;
export const noTopBorder: string;
export const noBottomBorder: string;
export const container: string;
export const contentWrapper: string;
