// Generated by ./dev/css-typed/index.mts, DO NOT EDIT IT!!!
// source file: WikiBeginnerEditor.module.less

export const flex: string;
export const flexCol: string;
export const flex1: string;
export const justifyBetween: string;
export const justifyCenter: string;
export const itemsCenter: string;
export const textCenter: string;
export const hFull: string;
export const wFull: string;
export const truncate: string;
export const hidden: string;
export const smScreenHidden: string;
export const noTopBorder: string;
export const noBottomBorder: string;
export const wikiEditor: string;
export const editorItem: string;
export const editorItemInput: string;
export const editorItemInputGroup: string;
export const editorItemInputGroupSecondary: string;
export const editorItemMinus: string;
export const editorItemConvertHandler: string;
export const editorItemTopRadius: string;
export const footer: string;
export const footerBtn: string;
export const footerPlaceholder: string;
