// Generated by @bangumi/dev/css-typed
// source file: WikiBeginnerEditor.module.less

export const smScreenHidden: string;
export const noTopBorder: string;
export const noBottomBorder: string;
export const wikiEditor: string;
export const editorItem: string;
export const editorItemInput: string;
export const editorItemInputGroup: string;
export const editorItemInputGroupSecondary: string;
export const editorItemMinus: string;
export const editorItemConvertHandler: string;
export const editorItemTopRadius: string;
export const footer: string;
export const footerBtn: string;
export const footerPlaceholder: string;
