// Generated by @bangumi/dev/css-typed
// source file: WikiLayout.module.less

export const smScreenHidden: string;
export const noTopBorder: string;
export const noBottomBorder: string;
export const title: string;
export const subTitle: string;
export const body: string;
