// Generated by ./dev/css-typed
// source file: style.module.less

export const smScreenHidden: string;
export const noTopBorder: string;
export const noBottomBorder: string;
export const errorContainer: string;
export const errorLayout: string;
export const title: string;
export const content: string;
export const info: string;
export const footer: string;
export const footerDivider: string;
