// Generated by ./dev/css-typed DO NOT EDIT IT
// source file: UserHome.module.less

export const smScreenHidden: string;
export const noTopBorder: string;
export const noBottomBorder: string;
export const pageContainer: string;
export const greets: string;
