// Generated by @bangumi/dev/css-typed
// source file: style.module.less

export const smScreenHidden: string;
export const noTopBorder: string;
export const noBottomBorder: string;
export const footerContainer: string;
export const footerMain: string;
export const inner: string;
export const footerLeft: string;
export const logo: string;
export const copyright: string;
export const footerRight: string;
export const block: string;
export const title: string;
