// Generated by ./dev/css-typed/index.mts, DO NOT EDIT IT!!!
// source file: style.module.less

export const flex: string;
export const flexCol: string;
export const flex1: string;
export const justifyBetween: string;
export const justifyCenter: string;
export const itemsCenter: string;
export const textCenter: string;
export const hFull: string;
export const wFull: string;
export const truncate: string;
export const hidden: string;
export const smScreenHidden: string;
export const noTopBorder: string;
export const noBottomBorder: string;
export const footerContainer: string;
export const footerMain: string;
export const inner: string;
export const footerLeft: string;
export const logo: string;
export const copyright: string;
export const footerRight: string;
export const block: string;
export const title: string;
