// Generated by ./dev/css-typed
// source file: GroupInfo.module.less

export const smScreenHidden: string;
export const noTopBorder: string;
export const noBottomBorder: string;
export const groupInfo: string;
export const groupDetails: string;
export const groupDescription: string;
export const groupOpinions: string;
