// Generated by ./dev/css-typed
// source file: GroupLayout.module.less

export const smScreenHidden: string;
export const noTopBorder: string;
export const noBottomBorder: string;
export const pageContainer: string;
export const newMembers: string;
