// Generated by ./dev/css-typed
// source file: GroupNavigation.module.less

export const smScreenHidden: string;
export const noTopBorder: string;
export const noBottomBorder: string;
export const wrapper: string;
export const section: string;
export const links: string;
