// Generated by @bangumi/dev/css-typed
// source file: GroupHeader.module.less

export const smScreenHidden: string;
export const noTopBorder: string;
export const noBottomBorder: string;
export const groupHeader: string;
export const title: string;
export const thumbnail: string;
export const infoCol: string;
