// Generated by ./dev/css-typed DO NOT EDIT IT
// source file: TopicForm.module.less

export const smScreenHidden: string;
export const noTopBorder: string;
export const noBottomBorder: string;
export const titleInput: string;
export const contentEditor: string;
export const quickPostForm: string;
