// Generated by @bangumi/dev/css-typed
// source file: UserCard.module.less

export const smScreenHidden: string;
export const noTopBorder: string;
export const noBottomBorder: string;
export const userCard: string;
export const vertical: string;
export const horizontal: string;
export const avatar: string;
export const nickname: string;
