name: 'Setup Node and run pnpm i'
description: 'setup node env'
runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version-file: '.node-version'

    - run: |
        npm i -g corepack
        corepack enable
        corepack prepare --activate
        pnpm --version
      shell: bash
      name: install pnpm

    - uses: actions/cache@v4
      with:
        path: ~/.local/share/pnpm/store/
        key: ${{ runner.os }}-1-node${{ inputs.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-1-node${{ inputs.node-version }}-

    - name: Install Dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
