name: 'Setup Node and run npm ci'
description: 'run actions/setup-node and `npm ci`'
runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v2.2.4
      with:
        version: '7'
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version-file: '.node-version'
        cache: 'pnpm'

    - name: Install Dependencies
      run: pnpm install
      shell: bash
