// Generated by ./dev/css-typed DO NOT EDIT IT
// source file: TopicsTable.module.less

export const smScreenHidden: string;
export const noTopBorder: string;
export const noBottomBorder: string;
export const flex: string;
export const flexCol: string;
export const flex1: string;
export const justifyBetween: string;
export const justifyCenter: string;
export const itemsCenter: string;
export const textCenter: string;
export const hFull: string;
export const wFull: string;
export const truncate: string;
export const hidden: string;
export const topicTable: string;
export const updateTime: string;
export const title: string;
export const author: string;
export const replies: string;
