// Generated by ./dev/css-typed
// source file: index.module.less

export const smScreenHidden: string;
export const noTopBorder: string;
export const noBottomBorder: string;
export const topicActions: string;
export const replies: string;
export const replyFormContainer: string;
export const replyForm: string;
