// Generated by ./dev/css-typed DO NOT EDIT IT
// source file: WikiEditor.module.less

export const smScreenHidden: string;
export const noTopBorder: string;
export const noBottomBorder: string;
export const editor: string;
