// Generated by @bangumi/dev/css-typed
// source file: WikiEditor.module.less

export const smScreenHidden: string;
export const noTopBorder: string;
export const noBottomBorder: string;
export const editor: string;
