// Generated by @bangumi/dev/css-typed
// source file: GroupTopicHeader.module.less

export const smScreenHidden: string;
export const noTopBorder: string;
export const noBottomBorder: string;
export const groupTopicHeader: string;
export const headerMain: string;
export const navBar: string;
export const title: string;
