/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/p1/logout': {
    /** @description 登出 */
    post: operations['logout'];
  };
  '/p1/login': {
    /**
     * @description 需要 [hCaptcha的验证码](https://docs.hcaptcha.com/#add-the-hcaptcha-widget-to-your-webpage)
     *
     * site-key 是 `4874acee-9c6e-4e47-99ad-e2ea1606961f`
     */
    post: operations['login'];
  };
  '/p1/me': {
    get: operations['getCurrentUser'];
  };
  '/p1/groups/{groupName}/profile': {
    /** @description 获取小组首页 */
    get: operations['getGroupProfile'];
  };
  '/p1/groups/-/topics/{id}': {
    /** @description 获取帖子列表 */
    get: operations['getGroupTopic'];
  };
  '/p1/groups/{groupName}/members': {
    /** @description 获取帖子列表 */
    get: operations['listGroupMembersByName'];
  };
  '/p1/groups/{groupName}/topics': {
    /** @description 获取帖子列表 */
    get: operations['getGroupTopicsByGroupName'];
  };
  '/p1/subjects/{subjectID}/topics': {
    /** @description 获取帖子列表 */
    get: operations['getSubjectTopicsBySubjectId'];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** User */
    User: {
      id: number;
      username: string;
      nickname: string;
      /** Avatar */
      avatar: {
        small: string;
        medium: string;
        large: string;
      };
      sign: string;
      user_group: number;
    };
    /** Avatar */
    Avatar: {
      small: string;
      medium: string;
      large: string;
    };
    /** @description fastify default error response */
    Error: {
      code: string;
      error: string;
      message: string;
      statusCode: number;
    };
    /** Topic */
    Topic: {
      /** @description topic id */
      id: number;
      /** User */
      creator: {
        id: number;
        username: string;
        nickname: string;
        /** Avatar */
        avatar: {
          small: string;
          medium: string;
          large: string;
        };
        sign: string;
        user_group: number;
      };
      title: string;
      /** @description 小组/条目ID */
      parentID: number;
      /** @description 发帖时间，unix time stamp in seconds */
      createdAt: number;
      /** @description 最后回复时间，unix time stamp in seconds */
      updatedAt: number;
      repliesCount: number;
    };
    GroupMember: {
      /** Avatar */
      avatar: {
        small: string;
        medium: string;
        large: string;
      };
      id: number;
      nickname: string;
      username: string;
      joinedAt: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {
  logout: {
    /** @description 登出 */
    responses: {
      /** @description Default Response */
      200: {
        content: {
          'application/json': Record<string, never>;
        };
      };
      /** @description 未登录 */
      401: {
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description 意料之外的服务器错误 */
      500: {
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
  login: {
    /**
     * @description 需要 [hCaptcha的验证码](https://docs.hcaptcha.com/#add-the-hcaptcha-widget-to-your-webpage)
     *
     * site-key 是 `4874acee-9c6e-4e47-99ad-e2ea1606961f`
     */
    requestBody: {
      content: {
        'application/json': {
          email: string;
          password: string;
          'h-captcha-response': string;
        };
      };
    };
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          /** @description example: "sessionID=12345abc" */
          'Set-Cookie'?: string;
        };
        content: {
          'application/json': components['schemas']['User'];
        };
      };
      /** @description 缺少字段等 */
      400: {
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description 验证码错误/账号密码不匹配 */
      401: {
        headers: {
          /** @description remaining rate limit */
          'X-RateLimit-Remaining'?: number;
          /** @description total limit per 10 minutes */
          'X-RateLimit-Limit'?: number;
          /** @description seconds to reset rate limit */
          'X-RateLimit-Reset'?: number;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description 失败次数太多，需要过一段时间再重试 */
      429: {
        headers: {
          /** @description remaining rate limit */
          'X-RateLimit-Remaining'?: number;
          /** @description limit per 10 minutes */
          'X-RateLimit-Limit'?: number;
          /** @description seconds to reset rate limit */
          'X-RateLimit-Reset'?: number;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description 意料之外的服务器错误 */
      500: {
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
  getCurrentUser: {
    responses: {
      /** @description Default Response */
      200: {
        content: {
          'application/json': components['schemas']['User'];
        };
      };
      /** @description Default Response */
      401: {
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description 意料之外的服务器错误 */
      500: {
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
  getGroupProfile: {
    /** @description 获取小组首页 */
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      path: {
        groupName: string;
      };
    };
    responses: {
      /** @description Default Response */
      200: {
        content: {
          'application/json': {
            recentAddedMembers: {
              /** Avatar */
              avatar: {
                small: string;
                medium: string;
                large: string;
              };
              id: number;
              nickname: string;
              username: string;
              joinedAt: number;
            }[];
            topics: components['schemas']['Topic'][];
            /** @description 是否已经加入小组 */
            inGroup: boolean;
            group: {
              id: number;
              name: string;
              nsfw: boolean;
              title: string;
              icon: string;
              description: string;
              totalMembers: number;
              createdAt: number;
            };
            totalTopics: number;
          };
        };
      };
      /** @description 小组不存在 */
      404: {
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description 意料之外的服务器错误 */
      500: {
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
  getGroupTopic: {
    /** @description 获取帖子列表 */
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Default Response */
      200: {
        content: {
          'application/json': {
            id: number;
            group: {
              id: number;
              name: string;
              nsfw: boolean;
              title: string;
              icon: string;
              description: string;
              totalMembers: number;
              createdAt: number;
            };
            /** User */
            creator: {
              id: number;
              username: string;
              nickname: string;
              /** Avatar */
              avatar: {
                small: string;
                medium: string;
                large: string;
              };
              sign: string;
              user_group: number;
            };
            title: string;
            text: string;
            state: number;
            createdAt: number;
            replies: {
              id: number;
              isFriend: boolean;
              replies: {
                id: number;
                /** User */
                creator: {
                  id: number;
                  username: string;
                  nickname: string;
                  /** Avatar */
                  avatar: {
                    small: string;
                    medium: string;
                    large: string;
                  };
                  sign: string;
                  user_group: number;
                };
                createdAt: number;
                isFriend: boolean;
                text: string;
                state: number;
              }[];
              /** User */
              creator: {
                id: number;
                username: string;
                nickname: string;
                /** Avatar */
                avatar: {
                  small: string;
                  medium: string;
                  large: string;
                };
                sign: string;
                user_group: number;
              };
              createdAt: number;
              text: string;
              state: number;
            }[];
          };
        };
      };
      /** @description 小组不存在 */
      404: {
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description 意料之外的服务器错误 */
      500: {
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
  listGroupMembersByName: {
    /** @description 获取帖子列表 */
    parameters: {
      query?: {
        type?: 'mod' | 'normal' | 'all';
        limit?: number;
        offset?: number;
      };
      path: {
        groupName: string;
      };
    };
    responses: {
      /** @description Default Response */
      200: {
        content: {
          'application/json': {
            data: components['schemas']['GroupMember'][];
            total: number;
          };
        };
      };
      /** @description 小组不存在 */
      404: {
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description 意料之外的服务器错误 */
      500: {
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
  getGroupTopicsByGroupName: {
    /** @description 获取帖子列表 */
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      path: {
        groupName: string;
      };
    };
    responses: {
      /** @description Default Response */
      200: {
        content: {
          'application/json': {
            data: components['schemas']['Topic'][];
            total: number;
          };
        };
      };
      /** @description 小组不存在 */
      404: {
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description 意料之外的服务器错误 */
      500: {
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
  getSubjectTopicsBySubjectId: {
    /** @description 获取帖子列表 */
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      path: {
        subjectID: number;
      };
    };
    responses: {
      /** @description Default Response */
      200: {
        content: {
          'application/json': {
            data: components['schemas']['Topic'][];
            total: number;
          };
        };
      };
      /** @description 条目不存在 */
      404: {
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description 意料之外的服务器错误 */
      500: {
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
}
