// Generated by ./dev/css-typed DO NOT EDIT IT
// source file: style.module.less

export const smScreenHidden: string;
export const noTopBorder: string;
export const noBottomBorder: string;
export const grid: string;
export const tipText: string;
export const groupLink: string;
