name: E2E Test

on:
  push:
    branches: [master]
    paths-ignore:
      - '**.md'
      - '.github/scripts/**'
  pull_request:
    branches: [master]
    paths-ignore:
      - '**.md'
      - '.github/scripts/**'

jobs:
  test-e2e:
    if: ${{ false }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: ./.github/actions/setup-js-env

      - name: Install Playwright
        run: pnpm --filter @bangumi/website run install-playwright-deps

      - name: Run test
        run: pnpm test:e2e

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: packages/website/playwright-report
