name: Release

on:
  schedule:
    - cron: '15 3 * * *'

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-js-env

      - name: Get Version
        id: version
        run: |
          today=$(date +%Y.%m.%d)
          count=$(git ls-remote --tags origin "${today}.*" | wc -l)
          echo "version=${today}.$((count + 1))" >> "$GITHUB_OUTPUT"

      - run: pnpm build
      - run: zip -r bangumi-website.zip ./packages/website/dist
      - run: openssl dgst -sha256 bangumi-website.zip > bangumi-website.zip.sha256

      - name: Upload Github Release
        run: gh release create "$VERSION" bangumi-website.zip bangumi-website.zip.sha256 --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.version.outputs.version }}
